### PR TITLE
[SCB-813] Fix the pack-contract-grpc build issue on macOSX

### PR DESCRIPTION
**Pull request by jeremyxu2010**
1. 升级依赖的protoc-gen-grpc-java版本，见 https://github.com/grpc/grpc-java/issues/1683

Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/SCB) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [ x ] Each commit in the pull request should have a meaningful subject line and body.
 - [ x ] Format the pull request title like `[SCB-XXX] Fixes bug in ApproximateQuantiles`, where you replace `SCB-XXX` with the appropriate JIRA issue.
 - [ x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ x ] Run `mvn clean install` to make sure basic checks pass. A more thorough check will be performed on your pull request automatically.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

---

### CODE REVIEW

**Comment by Uditmittal** [comment]
[ERROR] PROTOC FAILED: --java-pgv_out: protoc-gen-java-pgv: Plugin killed by signal 11.

**Comment by WillemJiang** [comment]
how did you run the JVM? I guess you may still need to use X86 interpreter.

**Comment by Uditmittal** [comment]
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Homebrew/Cellar/maven/3.6.3_1/libexec
Java version: 15.0.1, vendor: N/A, runtime: /usr/local/Homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "11.2.1", arch: "x86_64", family: "mac"


✗ java -version                                                    
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11)
OpenJDK 64-Bit Server VM (build 11.0.9+11, mixed mode)

**Comment by coolbeevip** [comment]
That might be helpful

https://github.com/grpc/grpc-java/issues/7690

**Pull request merged**
